### ISSUE TITLE
cleanup_old_data trying to use blobxfer even when not configured

### ISSUE THREAD

**Issue by dumbasPL** [tiredofit/docker-db-backup#175]
### Summary

blobxfer being called when `BACKUP_LOCATION` is set to `FILESYSTEM` (the default)

### Steps to reproduce

1. set `DB_CLEANUP_TIME` to any value that will trigger a cleanup
2. trigger a backup
3. observer error at the `Cleaning up old backups` stage

### What is the expected *correct* behavior?

blobxfer is only used when `BACKUP_LOCATION` is set to `blobxfer`

### Relevant logs and/or screenshots

```
2022-10-11T09:59:06.925550724Z 2022-10-11.09:59:06 [NOTICE] ** [db-backup] Dumping MongoDB database: '<redacted>' and compressing with gzip
2022-10-11T09:59:08.165765875Z 2022-10-11.09:59:08 [INFO] ** [db-backup] DB Backup of 'mongo_<redacted>_mongo_20221011-095906.archive.gz' completed successfully
2022-10-11T09:59:08.169914946Z 2022-10-11.09:59:08 [NOTICE] ** [db-backup] Generating MD5 for 'mongo_<redacted>_mongo_20221011-095906.archive.gz'
2022-10-11T09:59:08.217050902Z 2022-10-11.09:59:08 [NOTICE] ** [db-backup] Backup of mongo_<redacted>_mongo_20221011-095906.archive.gz created with the size of 11491480 bytes
2022-10-11T09:59:08.235168347Z 2022-10-11.09:59:08 [NOTICE] ** [db-backup] DB Backup for '<redacted>' time taken: Hours: 0 Minutes: 00 Seconds: 02
2022-10-11T09:59:08.240972975Z 2022-10-11.09:59:08 [INFO] ** [db-backup] Backup routines finish time: 2022-10-11 09:59:08 GMT with overall exit code 0
2022-10-11T09:59:08.246542033Z 2022-10-11.09:59:08 [NOTICE] ** [db-backup] Backup routines time taken: Hours: 0 Minutes: 00 Seconds: 02
2022-10-11T09:59:08.251182894Z 2022-10-11.09:59:08 [INFO] ** [db-backup] Cleaning up old backups
2022-10-11T09:59:08.257302210Z 2022-10-11.09:59:08 [INFO] ** [db-backup] Cleaning up old backups on S3 storage with blobxfer
2022-10-11T09:59:08.506539141Z Traceback (most recent call last):
2022-10-11T09:59:08.506553532Z   File "/usr/bin/blobxfer", line 8, in <module>
2022-10-11T09:59:08.506586901Z     sys.exit(cli())
2022-10-11T09:59:08.506616990Z   File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
2022-10-11T09:59:08.507034224Z     return self.main(*args, **kwargs)
2022-10-11T09:59:08.507041050Z   File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
2022-10-11T09:59:08.507517546Z     rv = self.invoke(ctx)
2022-10-11T09:59:08.507524194Z   File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
2022-10-11T09:59:08.508008552Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2022-10-11T09:59:08.508015254Z   File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
2022-10-11T09:59:08.508605033Z     return ctx.invoke(self.callback, **ctx.params)
2022-10-11T09:59:08.508611845Z   File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
2022-10-11T09:59:08.508988538Z     return __callback(*args, **kwargs)
2022-10-11T09:59:08.508995215Z   File "/usr/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
2022-10-11T09:59:08.509066981Z     return ctx.invoke(f, obj, *args, **kwargs)
2022-10-11T09:59:08.509073711Z   File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
2022-10-11T09:59:08.509392008Z     return __callback(*args, **kwargs)
2022-10-11T09:59:08.509398748Z   File "/usr/lib/python3.10/site-packages/blobxfer_cli/cli.py", line 1129, in upload
2022-10-11T09:59:08.509776225Z     ctx.initialize(settings.TransferAction.Upload)
2022-10-11T09:59:08.509783003Z   File "/usr/lib/python3.10/site-packages/blobxfer_cli/cli.py", line 68, in initialize
2022-10-11T09:59:08.509892128Z     self._init_config()
2022-10-11T09:59:08.509896032Z   File "/usr/lib/python3.10/site-packages/blobxfer_cli/cli.py", line 101, in _init_config
2022-10-11T09:59:08.510012978Z     settings.merge_global_settings(self.config, self.cli_options)
2022-10-11T09:59:08.510015678Z   File "/usr/lib/python3.10/site-packages/blobxfer_cli/settings.py", line 331, in merge_global_settings
2022-10-11T09:59:08.510234304Z     raise ValueError('azure storage settings not specified')
2022-10-11T09:59:08.510238309Z ValueError: azure storage settings not specified
2022-10-11T09:59:08.536427267Z 2022-10-11.09:59:08 [NOTICE] ** [db-backup] Sleeping for another 86398 seconds. Waking up at 2022-10-12 09:59:06 GMT 
```

### Environment

- Image version / tag: 3.5.0
- Host OS: Debian 11

### docker-compose
```yaml
version: '3.8'
services:
  mongo:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
  mongo-backup:
    image: tiredofit/db-backup:latest
    restart: always
    volumes:
      - ./backup:/backup
    environment:
      # - DEBUG_MODE=true
      - CONTAINER_ENABLE_MONITORING=false
      - DB_AUTH=admin
      - DB_TYPE=mongo
      - DB_HOST=mongo
      - DB_NAME=test
      - DB_USER=root
      - DB_PASS=test
      - DB_CLEANUP_TIME=1234
```
    
### Possible fixes

check if blobxfer is configured before trying to using it

**Comment by tiredofit** [comment]
Thanks for this one - I missed this during my review that it would get called during the cleanup process. I've added another check to solve this in `3.5.1` which is being built now.

**Comment by dumbasPL** [comment]
works :+1:
