### ISSUE TITLE
Blobxfer env variables are not supported within Docker SWARM secrets

### ISSUE THREAD

**Issue by jozefrebjak** [tiredofit/docker-db-backup#204]
`BLOBXFER_STORAGE_ACCOUNT` & `BLOBXFER_STORAGE_ACCOUNT_KEY` seems that they are not supported to use with Docker SWARM mode secrets feature like:

```
BLOBXFER_STORAGE_ACCOUNT_FILE
```

```
BLOBXFER_STORAGE_ACCOUNT_KEY_FILE
```

**Comment by tiredofit** [comment]
https://github.com/tiredofit/docker-db-backup/commit/1659e34fc78e16a253495aab464d6e55843de326 or `tiredofit/db-backup:3.7.5` should give this functionality.. Let me know how it works.

**Comment by jozefrebjak** [comment]
@tiredofit it doesn't work for me. 

```sh
  mariadb-backup:
    image: tiredofit/db-backup:3.7.5
    environment:
      BACKUP_LOCATION: blobxfer
      BLOBXFER_REMOTE_PATH: /database
      BLOBXFER_STORAGE_ACCOUNT_FILE: /run/secrets/BLOBXFER_STORAGE_ACCOUNT
      BLOBXFER_STORAGE_ACCOUNT_KEY_FILE: /run/secrets/BLOBXFER_STORAGE_ACCOUNT_KEY
      CHECKSUM: SHA1
      COMPRESSION: GZ
      CONTAINER_ENABLE_MONITORING: 'FALSE'
      DB_CLEANUP_TIME: '8640'
      DB_DUMP_BEGIN: '0000'
      DB_DUMP_FREQ: '1440'
      DB_HOST: mariadb
      DB_NAME: database
      DB_PASS_FILE: /run/secrets/GC_DATABASE_PASSWORD
      DB_TYPE: mariadb
      DB_USER:user
      DEBUG_MODE: 'TRUE'
      SPLIT_DB: 'FALSE'
      TIMEZONE: Europe/Bratislava
    secrets:
     - BLOBXFER_STORAGE_ACCOUNT
     - BLOBXFER_STORAGE_ACCOUNT_KEY
     - GC_DATABASE_PASSWORD
```

Debug:

```sh
+ var_true FALSE
+ '[' false = true ']'
+ '[' false = yes ']'
+ '[' blobxfer = s3 ']'
+ '[' blobxfer = minio ']'
+ '[' blobxfer = blobxfer ']'
+ '[' -n /run/secrets/BLOBXFER_STORAGE_ACCOUNT ']'
+ '[' -n /run/secrets/BLOBXFER_STORAGE_ACCOUNT_KEY ']'
+ file_env BLOBXFER_STORAGE_ACCOUNT_FILE
+ '[' true = true ']'
+ local var=BLOBXFER_STORAGE_ACCOUNT_FILE
+ local fileVar=BLOBXFER_STORAGE_ACCOUNT_FILE_FILE
+ local def=
+ local val=
+ '[' '' ']'
+ '[' /run/secrets/BLOBXFER_STORAGE_ACCOUNT ']'
+ val=/run/secrets/BLOBXFER_STORAGE_ACCOUNT
+ '[' -z /run/secrets/BLOBXFER_STORAGE_ACCOUNT ']'
+ export BLOBXFER_STORAGE_ACCOUNT_FILE=/run/secrets/BLOBXFER_STORAGE_ACCOUNT
+ BLOBXFER_STORAGE_ACCOUNT_FILE=/run/secrets/BLOBXFER_STORAGE_ACCOUNT
+ unset BLOBXFER_STORAGE_ACCOUNT_FILE_FILE
+ file_env BLOBXFER_STORAGE_ACCOUNT_KEY_FILE
+ '[' true = true ']'
+ local var=BLOBXFER_STORAGE_ACCOUNT_KEY_FILE
+ local fileVar=BLOBXFER_STORAGE_ACCOUNT_KEY_FILE_FILE
+ local def=
+ local val=
+ '[' '' ']'
+ '[' /run/secrets/BLOBXFER_STORAGE_ACCOUNT_KEY ']'
+ val=/run/secrets/BLOBXFER_STORAGE_ACCOUNT_KEY
+ '[' -z /run/secrets/BLOBXFER_STORAGE_ACCOUNT_KEY ']'
+ export BLOBXFER_STORAGE_ACCOUNT_KEY_FILE=/run/secrets/BLOBXFER_STORAGE_ACCOUNT_KEY
+ BLOBXFER_STORAGE_ACCOUNT_KEY_FILE=/run/secrets/BLOBXFER_STORAGE_ACCOUNT_KEY
+ unset BLOBXFER_STORAGE_ACCOUNT_KEY_FILE_FILE
+ '[' auto = manual ']'
+ '[' manual = manual ']'
+ DB_DUMP_BEGIN=+0
+ manual=TRUE
+ print_debug 'Detected Manual Mode'
+ output_off
+ '[' true = true ']'
+ set +x
```

skipped woring part and 

```sh
2023-03-04.08:49:43 [NOTICE] /etc/services.available/10-db-backup/run ** [db-backup] Backup of mysql_all_mariadb_20230304-084937.sql.gz created with the size of 1151006 bytes
+ case "${BACKUP_LOCATION,,}" in
+ print_info 'Moving backup to S3 Bucket with blobxfer'
+ output_off
+ '[' true = true ']'
+ set +x
2023-03-04.08:49:43 [INFO] /etc/services.available/10-db-backup/run ** [db-backup] Moving backup to S3 Bucket with blobxfer
+ mkdir -p /backup
+ mv /tmp/backups/mysql_all_mariadb_20230304-084937.sql.gz.sha1 /backup/
+ mv /tmp/backups/mysql_all_mariadb_20230304-084937.sql.gz /backup/mysql_all_mariadb_20230304-084937.sql.gz
+ silent blobxfer upload --mode file --remote-path /database --local-path /backup
+ '[' TRUE = true ']'
+ '[' '' = true ']'
+ '[' debug = debug ']'
+ blobxfer upload --mode file --remote-path /database --local-path /backup
Traceback (most recent call last):
  File "/usr/bin/blobxfer", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/blobxfer_cli/cli.py", line 1129, in upload
    ctx.initialize(settings.TransferAction.Upload)
  File "/usr/lib/python3.10/site-packages/blobxfer_cli/cli.py", line 68, in initialize
    self._init_config()
  File "/usr/lib/python3.10/site-packages/blobxfer_cli/cli.py", line 101, in _init_config
    settings.merge_global_settings(self.config, self.cli_options)
  File "/usr/lib/python3.10/site-packages/blobxfer_cli/settings.py", line 331, in merge_global_settings
    raise ValueError('azure storage settings not specified')
ValueError: azure storage settings not specified
```

**Comment by jozefrebjak** [comment]
@tiredofit it's not working till now. `BLOBXFER_STORAGE_ACCOUNT_FILE` is fine but `BLOBXFER_STORAGE_ACCOUNT_KEY_FILE` is not. Please check it.
