### ISSUE TITLE
Backup throw python error when use S3

### ISSUE THREAD

**Issue by khoazero123** [tiredofit/docker-db-backup#81]
### Summary

I use sample docker-compose.yml in the repo to test backup to S3, then I see the error in terminal:
```
ModuleNotFoundError: No module named 'six'
```

### Steps to reproduce

1. Use sample [docker-compose.yml](https://github.com/tiredofit/docker-db-backup/blob/master/examples/docker-compose.yml) and add the S3 variables: `BACKUP_LOCATION=S3`, ...
2. Run `docker-compose up`

### What is the expected *correct* behavior?

Should no error when using S3 and the backup files uploaded to S3.

### Relevant logs and/or screenshots

```
example-db-backup    | Traceback (most recent call last):
example-db-backup    |   File "/usr/bin/aws", line 19, in <module>
example-db-backup    |     import awscli.clidriver
example-db-backup    |   File "/usr/lib/python3.9/site-packages/awscli/clidriver.py", line 17, in <module>
example-db-backup    |     import botocore.session
example-db-backup    |   File "/usr/lib/python3.9/site-packages/botocore/session.py", line 29, in <module>
example-db-backup    |     import botocore.configloader
example-db-backup    |   File "/usr/lib/python3.9/site-packages/botocore/configloader.py", line 19, in <module>
example-db-backup    |     from botocore.compat import six
example-db-backup    |   File "/usr/lib/python3.9/site-packages/botocore/compat.py", line 27, in <module>
example-db-backup    |     from dateutil.tz import tzlocal
example-db-backup    |   File "/usr/lib/python3.9/site-packages/dateutil/tz/__init__.py", line 2, in <module>
example-db-backup    |     from .tz import *
example-db-backup    |   File "/usr/lib/python3.9/site-packages/dateutil/tz/tz.py", line 19, in <module>
example-db-backup    |     import six
example-db-backup    | ModuleNotFoundError: No module named 'six'
```

### Environment

- Image version / tag:  tiredofit/db-backup:latest
- Host OS: ubuntu 20

<details>
<summary>Full logs</summary>

```log
example-db           | 2021-10-14 00:51:12+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
example-db           | 2021-10-14 00:51:12+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
example-db           | 2021-10-14 00:51:12+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
example-db           | 2021-10-14  0:51:12 0 [Note] mysqld (server 10.6.4-MariaDB-1:10.6.4+maria~focal) starting as process 1 ...
example-db           | 2021-10-14  0:51:12 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
example-db           | 2021-10-14  0:51:12 0 [Note] InnoDB: Number of pools: 1
example-db           | 2021-10-14  0:51:12 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
example-db           | 2021-10-14  0:51:12 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
example-db           | 2021-10-14  0:51:12 0 [Note] InnoDB: Using Linux native AIO
example-db           | 2021-10-14  0:51:12 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
example-db           | 2021-10-14  0:51:12 0 [Note] InnoDB: Completed initialization of buffer pool
example-db           | 2021-10-14  0:51:12 0 [Note] InnoDB: 128 rollback segments are active.
example-db           | 2021-10-14  0:51:12 0 [Note] InnoDB: Creating shared tablespace for temporary tables
example-db           | 2021-10-14  0:51:12 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
example-db           | 2021-10-14  0:51:12 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
example-db           | 2021-10-14  0:51:12 0 [Note] InnoDB: 10.6.4 started; log sequence number 42281; transaction id 14
example-db           | 2021-10-14  0:51:12 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
example-db           | 2021-10-14  0:51:12 0 [Note] Plugin 'FEEDBACK' is disabled.
example-db           | 2021-10-14  0:51:12 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
example-db           | 2021-10-14  0:51:12 0 [Note] InnoDB: Buffer pool(s) load completed at 211014  0:51:12
example-db           | 2021-10-14  0:51:12 0 [Note] Server socket created on IP: '0.0.0.0'.
example-db           | 2021-10-14  0:51:12 0 [Note] Server socket created on IP: '::'.
example-db           | 2021-10-14  0:51:12 0 [Warning] 'proxies_priv' entry '@% root@32c18de7e189' ignored in --skip-name-resolve mode.
example-db           | 2021-10-14  0:51:12 0 [Note] mysqld: ready for connections.
example-db           | Version: '10.6.4-MariaDB-1:10.6.4+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
example-db-backup    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
example-db-backup    | [s6-init] ensuring user provided files have correct perms...exited 0.
example-db-backup    | [fix-attrs.d] applying ownership & permissions fixes...
example-db-backup    | [fix-attrs.d] 00-functions: applying... 
example-db-backup    | [fix-attrs.d] 00-functions: exited 0.
example-db-backup    | [fix-attrs.d] 01-s6: applying... 
example-db-backup    | [fix-attrs.d] 01-s6: exited 0.
example-db-backup    | [fix-attrs.d] 02-zabbix: applying... 
example-db-backup    | [fix-attrs.d] 02-zabbix: exited 0.
example-db-backup    | [fix-attrs.d] 03-logrotate: applying... 
example-db-backup    | [fix-attrs.d] 03-logrotate: exited 0.
example-db-backup    | [fix-attrs.d] done.
example-db-backup    | [cont-init.d] executing container initialization scripts...
example-db-backup    | [cont-init.d] 00-startup: executing... 
example-db-backup    | [cont-init.d] 00-startup: exited 0.
example-db-backup    | [cont-init.d] 01-timezone: executing... 
example-db-backup    | [cont-init.d] 01-timezone: exited 0.
example-db-backup    | [cont-init.d] 02-permissions: executing... 
example-db-backup    | [cont-init.d] 02-permissions: exited 0.
example-db-backup    | [cont-init.d] 03-monitoring: executing... 
example-db-backup    | 2021-10-14-00:51:13 [NOTICE] ** [monitoring] Container configured for monitoring with 'zabbix modern'
example-db-backup    | [cont-init.d] 03-monitoring: exited 0.
example-db-backup    | [cont-init.d] 04-scheduling: executing... 
example-db-backup    | 2021-10-14-00:51:13 [NOTICE] ** [scheduling] Disabling Scheduling
example-db-backup    | [cont-init.d] 04-scheduling: exited 0.
example-db-backup    | [cont-init.d] 05-logging: executing... 
example-db-backup    | 2021-10-14-00:51:13 [NOTICE] ** [logging] Disabling Log Shipping Functionality
example-db-backup    | [cont-init.d] 05-logging: exited 0.
example-db-backup    | [cont-init.d] 06-messaging: executing... 
example-db-backup    | 2021-10-14-00:51:13 [NOTICE] ** [messaging] Disabling Container messaging features
example-db-backup    | [cont-init.d] 06-messaging: exited 0.
example-db-backup    | [cont-init.d] 99-container: executing... 
example-db-backup    | [cont-init.d] 99-container: exited 0.
example-db-backup    | [cont-init.d] done.
example-db-backup    | [services.d] starting services
example-db-backup    | [services.d] done.
example-db-backup    | 2021-10-14-00:51:13 [STARTING] ** [monitoring] [1] Starting Zabbix Agent (modern) 5.4.4
example-db-backup    | date: invalid date '@'
example-db-backup    | 2021-10-14-00:51:23 [NOTICE] ** [db-backup] Next Backup at 
example-db-backup    | 2021-10-14-00:51:23 [NOTICE] ** [db-backup] Dumping MariaDB database: example
example-db-backup    | 2021-10-14-00:51:23 [NOTICE] ** [db-backup] Compressing backup with gzip
example-db-backup    | 2021-10-14-00:51:23 [NOTICE] ** [db-backup] Generating MD5 for mysql_example_example-db_20211014-005123.sql.gz
example-db-backup    | 2021-10-14-00:51:23 [NOTICE] ** [db-backup] Backup of mysql_example_example-db_20211014-005123.sql.gz created with the size of 545 bytes
example-db-backup    | Traceback (most recent call last):
example-db-backup    |   File "/usr/bin/aws", line 19, in <module>
example-db-backup    |     import awscli.clidriver
example-db-backup    |   File "/usr/lib/python3.9/site-packages/awscli/clidriver.py", line 17, in <module>
example-db-backup    |     import botocore.session
example-db-backup    |   File "/usr/lib/python3.9/site-packages/botocore/session.py", line 29, in <module>
example-db-backup    |     import botocore.configloader
example-db-backup    |   File "/usr/lib/python3.9/site-packages/botocore/configloader.py", line 19, in <module>
example-db-backup    |     from botocore.compat import six
example-db-backup    |   File "/usr/lib/python3.9/site-packages/botocore/compat.py", line 27, in <module>
example-db-backup    |     from dateutil.tz import tzlocal
example-db-backup    |   File "/usr/lib/python3.9/site-packages/dateutil/tz/__init__.py", line 2, in <module>
example-db-backup    |     from .tz import *
example-db-backup    |   File "/usr/lib/python3.9/site-packages/dateutil/tz/tz.py", line 19, in <module>
example-db-backup    |     import six
example-db-backup    | ModuleNotFoundError: No module named 'six'
example-db-backup    | 2021-10-14-00:51:23 [NOTICE] ** [db-backup] Cleaning up old backups
example-db-backup    | 2021-10-14-00:51:23 [NOTICE] ** [db-backup] Found Custom Filesystem Scripts to Execute
example-db-backup    | 2021-10-14-00:51:23 [NOTICE] ** [db-backup] Running Script /assets/custom-scripts/post-script.sh
example-db-backup    | 0 mysql Backup Completed on example-db for example on 2021-10-14 00:51:23. Filename: mysql_example_example-db_20211014-005123.sql.gz Size: 545 bytes MD5: 82cd4a1dd66b0823b74621f171095ebe
```
</details>

<details>
  <summary>docker-compose.yml</summary>
  
```yml
version: '2'

services:
  example-db:
    container_name: example-db
    image: mariadb:latest
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=examplerootpassword
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=examplepassword
    restart: always

  example-db-backup:
    container_name: example-db-backup
    image: tiredofit/db-backup
    links:
     - example-db
    volumes:
      - ./backups:/backup
      - ./post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=example-db
      - DB_NAME=example
      - DB_USER=example
      - DB_PASS=examplepassword
      - DB_DUMP_FREQ=1440
      # - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - MD5=TRUE
      #- COMPRESSION=XZ
      - SPLIT_DB=TRUE

      - BACKUP_LOCATION=S3
      - S3_BUCKET=backup-database-001
      #- S3_HOSTNAME=
      - S3_KEY_ID=*********************************
      - S3_KEY_SECRET=*********************************
      - S3_PATH=ebook24h
    restart: always
```
</details>

**Comment by tiredofit** [comment]
Resolved 2e0c0d9248023341be92e8e052a25f768d194100 and tagged as `tiredofit:db-backup:2.8.2`
